### ISSUE TITLE
[HELP] how to constantly detect change in service variable value from another component?

### ISSUE THREAD

**Issue by nikhil-amin** [nikhil-amin/Notes-By-Nerds#1]
I can read service variable `loginStatus <Boolean>` from `user.service.ts` in component `nav-bar.component.ts`. But, i want it to get updated in `nav-bar.component.ts`  once the value of `loginStatus` is changed in `user.service.ts`. Any idea on how can i achieve this?

>  [user.service.ts](https://github.com/nikhil-amin/Notes-By-Nerds/blob/master/FrontEnd/src/app/shared/user.service.ts)
```
export class UserService {
  loginStatus = false;

  deleteToken() {
    this.loginStatus = false
    // other code....
  }

  isLoggedIn() {
    this.loginStatus = true
   // other code....
  }
}
```

> [nav-bar.component.ts](https://github.com/nikhil-amin/Notes-By-Nerds/blob/master/FrontEnd/src/app/nav-bar/nav-bar.component.ts)
```
export class NavBarComponent implements OnInit {
  constructor(private userService: UserService, private router: Router) { }
  LoginStatus:boolean = this.userService.loginStatus;
}
```

I would be grateful if someone can help me fix it or atleast give an hint on where i am making mistake.
Thanks in advance!

**Comment by sushinpv** [comment]
You want to detect changes  in service from a component right ?

If so then first create an Emitter in your service component which will emit any changes in the value,
Then use subscribe method on this particular emitter anywhere from your application( emitter object  will return a promise in terms of subscribe method)


Modified service class

export class UserService {
  @Output() loginStatusEmitter: EventEmitter<boolean> = new EventEmitter();
  loginStatus = false;

  deleteToken() {
    this.loginStatus = false;
    this.loginStatusEmitter.emit(this.loginStatus);
    // other code....
  }

  isLoggedIn() {
    this.loginStatus = true;
    this.loginStatusEmitter.emit(this.loginStatus);
   // other code....
  }
}

Modified Nav bar component

export class NavBarComponent implements OnInit {
  LoginStatus:boolean;
  constructor(private userService: UserService, private router: Router) {
     this.LoginStatus = this.userService.loginStatus;
  }
  //LoginStatus:boolean = this.userService.loginStatus; don't use this always use initialisation statement inside constructor 
  ngOnInit(){
      this.userService.loginStatusEmitter.subscribe(status => {
            this.LoginStatus = status;
      }
  }
}

**Comment by nikhil-amin** [comment]
Ok, Thanks a lot for the help. It is working now... 😄 ✌️
